version: 2

sources:
  - name: ASSESSMENT
    database: DBT_ASSESSMENT
    schema: ASSESSMENT
    tables:
      - name: ORDERS
      - name: CUSTOMERS

models:
  - name: stg_customers
    columns:
      - name: customer_id

  - name: stg_orders
    columns:
      - name: customer_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id