version: 2

sources:
  - name: ASSESSMENT
    database: DBT_ASSESSMENT
    schema: ASSESSMENT
    tables:
      - name: ORDERS

models:
  - name: stg_customers
    columns:
      - name: customer_id

  - name: stg_orders
    columns:
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id
              